### ISSUE TITLE
Minimal example?

### ISSUE THREAD

**Issue by dizcza** [liebman/esp32-gps-ntp#2]
Hi, you've pointed out this repository in a discussion on the ESP32 forum.
Thanks for making the project available and open.
It does contain though things are not strictly related to DS3231+GPS synchronization. In particular, lots of code seem to be required just for a display to work. Could you please provide a minimal code that shows how to use an RTC with a GPS module?
You've described several things in the readme but I don't see the backbone - RTC+GPS sync. And there are several files in this repo, as I mentioned, some scripts are unrelated. I'm lost here.
It'd be helpful if you somehow point to and/or describe the synchronization part standalone.
Thank you.

**Comment by liebman** [comment]
This is a bit rambling but maybe it will help:

The biggest trick was to use a high level interrupt (highint5.S) as that was the only way to service interrupts with consistently low latency.  This tracks time in microseconds for both GPS and PPS 1hz signals.

See `SyncManager.cpp`.  In particular `setTime()` sets the DS3231 time carefully to align as closely as possible with the DPS second change.  Also `recordOfset()`/`getOffset()` take the output from the `highint5` interrupt handler and generate an average delta that was measured between the two (GPS & DS3231) 1hz interrupt signals.  This average is used in a PID algorithm in `manageDrift()` to calculate a running correction and use it to adjust the AGE_OFFSET register to speed up or slow down the DS3231 to keep it in sync with GPS.  The `process()` function also handles when the DS3231 too far off to fix with AGE_OFFSET adjustments, and in that case it just sets the clock with `setTime()`.

**Comment by dizcza** [comment]
Thanks, I'm currently inspecting the code. `highint5` routine is written in assembly, really love it (though I still don't understand assembly).
Two questions so far.
1. What's the GPS module you're using?
2. I'm running into an error while building the project:
```
../components/lvgl_esp32_drivers/lvgl_tft/ili9341.c: In function 'ili9341_init':
../components/lvgl_esp32_drivers/lvgl_tft/ili9341.c:94:9: error: implicit declaration of function 'gpio_pad_select_gpio'; did you mean 'esp_rom_gpio_pad_select_gpio'? [-Werror=implicit-function-declaration]
         gpio_pad_select_gpio(ILI9341_DC);
         ^~~~~~~~~~~~~~~~~~~~
         esp_rom_gpio_pad_select_gpio
```
I'm using the latest ESP-IDF master branch v5.0-dev-1373-g84d11d1c3e to build ESP32 projects. I could find neither declaration nor implementation of the `gpio_pad_select_gpio` function in the repo and its submodules.

**Comment by dizcza** [comment]
All right, had to add
* `#include "rom/gpio.h"` in `ili9341.h` and
* `#include "soc/timer_group_struct.h"` in `MicroSecondTimer.h`
but now I get 
```
In file included from ../main/MicroSecondTimer.h:30,
                 from ../main/PPS.h:33,
                 from ../main/NTP.h:27,
                 from ../main/NTP.cpp:25:
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note: candidate: 'constexpr timg_txupdate_reg_t& timg_txupdate_reg_t::operator=(const timg_txupdate_reg_t&)'
 } timg_txupdate_reg_t;
   ^~~~~~~~~~~~~~~~~~~
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note:   no known conversion for argument 1 from 'int' to 'const timg_txupdate_reg_t&'
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note: candidate: 'constexpr timg_txupdate_reg_t& timg_txupdate_reg_t::operator=(timg_txupdate_reg_t&&)'
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note:   no known conversion for argument 1 from 'int' to 'timg_txupdate_reg_t&&'
In file included from ../main/PPS.h:33,
                 from ../main/NTP.h:27,
                 from ../main/NTP.cpp:25:
../main/MicroSecondTimer.h:47:42: error: 'volatile struct timg_hwtimer_reg_t' has no member named 'cnt_low'
         return TIMERG0.hw_timer[TIMER_0].cnt_low;
                                          ^~~~~~~
../main/MicroSecondTimer.h: In member function 'uint32_t MicroSecondTimer::getValue()':
../main/MicroSecondTimer.h:56:44: error: no match for 'operator=' (operand types are 'volatile timg_txupdate_reg_t' and 'int')
         TIMERG0.hw_timer[TIMER_0].update = 1;
                                            ^
In file included from ../main/MicroSecondTimer.h:30,
                 from ../main/PPS.h:33,
                 from ../main/NTP.h:27,
                 from ../main/NTP.cpp:25:
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note: candidate: 'constexpr timg_txupdate_reg_t& timg_txupdate_reg_t::operator=(const timg_txupdate_reg_t&)'
 } timg_txupdate_reg_t;
   ^~~~~~~~~~~~~~~~~~~
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note:   no known conversion for argument 1 from 'int' to 'const timg_txupdate_reg_t&'
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note: candidate: 'constexpr timg_txupdate_reg_t& timg_txupdate_reg_t::operator=(timg_txupdate_reg_t&&)'
/media/dizcza/media/esp-idf/components/soc/esp32/include/soc/timer_group_struct.h:98:3: note:   no known conversion for argument 1 from 'int' to 'timg_txupdate_reg_t&&'
In file included from ../main/PPS.h:33,
                 from ../main/NTP.h:27,
                 from ../main/NTP.cpp:25:
../main/MicroSecondTimer.h:57:42: error: 'volatile struct timg_hwtimer_reg_t' has no member named 'cnt_low'
         return TIMERG0.hw_timer[TIMER_0].cnt_low;
```
so I cannot build it with the newest ESP-IDF version. I need to know the ESP-IDF version this project was built with.

**Comment by liebman** [comment]
IDF version 4.2
Note: I use `platformio` in most of my projects because it handles installing idf and tools (or development tools for many other platforms) without me having to manage it.

**Comment by liebman** [comment]
For the GPS modules [this one](https://smile.amazon.com/gps/dp/B084MK8BS2) should work.  As well as [this one](https://smile.amazon.com/gp/product/B01H1R8BK0).

**Comment by dizcza** [comment]
Thanks for the link, I've ordered three Neo-6M.

I've managed to build your project in the latest ESP-IDF version. Had to change several things, including a line here and there in the LVGL submodules. If you want, I could come up with a pull request with fixes once I understand the logic.
I see many debug lines like `#if 1... endif`, even in the `highint5` assembly file. Hope the way it's now is the working version and I don't need to comment/uncomment them out.

There are several options in the menuconfig, but I see the most important ones are in the `PPS.h`:

https://github.com/liebman/esp32-gps-ntp/blob/master/main/PPS.h#L35-L36

I have a feeling that I need to uncomment these both lines, right?

**Comment by liebman** [comment]
No need to uncomment those - they were used when I was testing the `highint5` code and could be horribly broken.

A PR would be great, best if it can compile with both the old and new versions of IDF.

**Comment by dizcza** [comment]
> No need to uncomment those - they were used when I was testing the highint5 code and could be horribly broken.
Ah, great, these defines cover quite a lot of code that I don't need to look into. And yes, uncommenting them breaks the build.

There are also `LATENCY_OUTPUT` and `SYNC_LATENCY_OUTPUT` that are never defined. I think I won't need them either.

> best if it can compile with both the old and new versions of IDF

then we need to get rid of hard-coded things

https://github.com/liebman/esp32-gps-ntp/blob/master/main/MicroSecondTimer.h#L46

and move to public API (uncomment the following lines in both timer functions). I don't know how much calling a function brings overhead, perhaps a dozen of nS which is tolerable for the precision of tens of uS.

**Comment by liebman** [comment]
I used `LATENCY_OUTPUT` and `SYNC_LATENCY_OUTPUT` to toggle GPIOs to measure ISR latency.

You can use this to `#if` on the IDF version for specific features.  I want to keep the direct hardware access for the timer if possible.

```
#include "esp_idf_version.h"

#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(4, 0, 0)
    // enable functionality present in IDF v4.0
#endif
```

**Comment by dizcza** [comment]
I got it working (without a display - I've detached the display part and print everything to console).

The biggest question is: are entries in the `_offset_data` array (see SyncManager) reset on each second elapsed or they are getting accumulated with time? I mean if we comment out this line

https://github.com/liebman/esp32-gps-ntp/blob/75a73ee038aa825654ca1d235904e0fa9925be06/main/SyncManager.cpp#L303

and keep track of the `offset` in microseconds, is this offset calculated since the timepoint when GPS got valid? Or after each second there is logic in `highint5.S` that waits for the completion of a second (synchronization) on both PPS (GPS and RTC) and resets the values in the `_offset_data`? Looks like the former. In that case, the PPM is fairly simple:

```
PPM = offset / time_sec
```

where `offset` is the offset in us and `time_sec` is the elapsed seconds since the GPS fix. Correct?

For example, I've fixed the aging offset to the best value (-8 for a particular DS3231), waited for two hours, and got the offset `~170` us. The PPM, in this case, is `~0.025`.

**Comment by dizcza** [comment]
Looks like the `offset` is calculated from the absolute last time the `SyncManager.setTime()` was called (even if it was issued in a previous launch of the program), not from the time of a GPS fix. If it's true, then it makes sense to call this function on each launch after a GPS fix is obtained.

**Comment by liebman** [comment]
> Looks like the `offset` is calculated from the absolute last time the `SyncManager.setTime()` was called (even if it was issued in a previous launch of the program), not from the time of a GPS fix. If it's true, then it makes sense to call this function on each launch after a GPS fix is obtained.

`SyncManager .setTime()` is only called if the time difference between GPS time and the RTC is too great to adjust slowly (speeding up or slowing down the RTC with the aging offset).

**Comment by liebman** [comment]
IIRC, its been a couple of years, I used the `_offset_data` array to "smooth" out the jitter that is still present in the computed offset.

**Comment by dizcza** [comment]
Well, you commented on something that I already figured out from the code. I guess it's hard to dive freely into a two-years old project event it's yours :) Same for me.
There is a number of mistakes or misunderstanding that I also found.
1. The target in https://github.com/liebman/esp32-gps-ntp/blob/75a73ee038aa825654ca1d235904e0fa9925be06/main/SyncManager.cpp#L259 should always be zero. Otherwise, you're forcing the RTC to have a constant offset in us from the GPS (why would you?), and the integrals are jumping crazily.
2. An extra zero in the upper-bound (`10000050` -> `1000050`) in https://github.com/liebman/esp32-gps-ntp/blob/75a73ee038aa825654ca1d235904e0fa9925be06/main/SyncManager.cpp#L132
3. The `SyncManager.setTime()` is called frequently upon a change in seconds between the GPS and RTC modules. Once the seconds mismatch, the time is reset but in a couple of seconds, a mismatch in seconds happens again even though the offset is close to zero microseconds. Something fishy is going on here, I cannot catch the behavior. Need to wrap my head around that.

I leave it here for reference in case you'll want to revise the project in the future. I'm working on it anyway 'cause I couldn't find any other reliable sources to sync an RTC with a GPS. And I appreciate the effort you put in the assembly instructions to squeeze every microsecond precision out of cheap DS3231 modules.

**Comment by liebman** [comment]
1. Yes the target is usually 0, but I would set it via the display/GUI to various other values to test how the PID loop reacted for tuning.
2. nice catch!
3. that should not happen, I'll see if that happens in the one I built: NTP server running here for 2 years :-)

**Comment by liebman** [comment]
OK for #3 I think I know whats happening.  And I see in my local tree that I have an uncommitted change that I forgot I was testing:
When the GPS module (at least the inexpensive ones that I have) first reports its "valid" the time can still be off by a second or two and some minutes later it corrects.  This would cause 2 calls to setTime at the start, even if the RTC was correct. The committed code waits till the gps has been "valid" for 60 seconds, many times thats not long enough.  I had 20 minutes in my uncommitted changes. I'm going to try to clean up the code today, removing a lot of dead #ifdef'd out code.

**Comment by dizcza** [comment]
That would be superhelpful. Thanks.
I'm not sure though if that's the culprit. I see multiple calls one after the other, not just two in a row. And typically, if say RTC is slower by 1 sec, then on the following second's mismatch the RTC's time will be again slower by 1 sec.

**Comment by liebman** [comment]
That sounds really odd.  If you can hook up a display it has some statistics for both PPS signals, if not then maybe you can print the same information periodically. 
![image](https://user-images.githubusercontent.com/1796060/152654395-ffb3835b-a63c-4fa8-b1e8-2cf7894b5ee5.png)
It almost sounds like its counting extra times.  Can you post what pin's you're using for the RTC PPS and the GPS PPS? Asking because there is an issue with using more than one GPIO edge interrupt in the same group where GPIO0 ~ GPIO31 is Group1 and GPIO32 ~ GPIO39 is Group2. See [this for details](https://www.espressif.com/sites/default/files/documentation/eco_and_workarounds_for_bugs_in_esp32_en.pdf). I use pins 26 and 35.

**Comment by dizcza** [comment]
Yes, I'm printing this info. I rarely see short or long PPS pulses from a GPS module, but I do see short & long (mostly long) PPS pulses from an RTC. I haven't gathered exact stats of how frequently this happens.

I've changed the `SyncManager.process()` to:

```c
    ...

    struct timeval gps_tv;
    struct timeval rtc_tv;
    _gpspps->getTime(&gps_tv);
    _rtcpps->getTime(&rtc_tv);
 
    // only if GPS is valid and not too close to the start or end of a second!
    if (gps_tv.tv_usec > 800000 && gps_tv.tv_usec < 900000)
    {
        if (abs(offset) > RTC_DRIFT_MAX || gps_tv.tv_sec != rtc_tv.tv_sec)
        {
            setTime();
            ESP_LOGW(TAG, "time correction happened!  PPS offset=%0.3f us gps_time=%ld rtc_time=%ld", offset, gps_tv.tv_sec, rtc_tv.tv_sec);
            struct timeval tv;
            _rtcpps->getTime(&tv);
            settimeofday(&tv, nullptr);
            resetOffset();
            return;
        }
    }

    manageDrift(offset);
```

So I've removed the `interval` of 10 sec (I find it arbitrary) and don't call `manageDrift(offset)` only if two conditions are met (the return statement is moved). I understand the internal `if (abs(offset) > RTC_DRIFT_MAX || gps_tv.tv_sec != rtc_tv.tv_sec)`, but I still struggle to grasp a need for the `if (gps_tv.tv_usec > 800000 && gps_tv.tv_usec < 900000)`. The comment didn't help me. I found the same check in the `app_main()`.

I understand this line https://github.com/liebman/esp32-gps-ntp/blob/75a73ee038aa825654ca1d235904e0fa9925be06/main/SyncManager.cpp#L379

though I haven't measured the i2c write time.

This function

```c
time_t PPS::getTime(struct timeval* tv)
{
    if (tv == nullptr)
    {
        return _data->pps_time;
    }

    // edge case!  both seconds and _last_timer only change once a second, however,
    // it changes via an interrupt so we make sure we have good values by making sure
    // it is the same on second look
    do
    {
        tv->tv_sec  = _data->pps_time;
        tv->tv_usec = _timer.getValue() - _data->pps_last;
        // timer could be slightly off, insure microseconds is not returned as (or more) than a full second!
        if (tv->tv_usec > 999999)
        {
            tv->tv_usec = 999999;
        }
    } while (tv->tv_sec != _data->pps_time); // insure we stay on the same seconds (to go with the microseconds)
    return tv->tv_sec;
}
```

also looks strange to me. I understand that the `_data->pps_time` can be changed after `tv->tv_sec  = _data->pps_time` but if we allow `tv->tv_usec = 999999` (only 1 us is left) then on the return point the `_data->pps_time` could be incremented.

I think the issue I get comes from these hardcoded timing offsets. I'm trying to strip out every non-needed complexity from the code. In progress...

-----

My GPIO is:

```
#define GPS_RX_PIN (GPIO_NUM_23)
#define GPS_TX_PIN (GPIO_NUM_19)
#define GPS_PPS_PIN ((gpio_num_t)GPIO_NUM_18)
#define RTC_PPS_PIN ((gpio_num_t)GPIO_NUM_5)
#define SDA_PIN (GPIO_NUM_4)
#define SCL_PIN (GPIO_NUM_22)
```

> Asking because there is an issue with using more than one GPIO edge interrupt in the same group where GPIO0 ~ GPIO31 is Group1 and GPIO32 ~ GPIO39 is Group2.

Thanks, I didn't know that. So I do have both interrupts within same group. I'll hook one of them to another group and let you know.

**Comment by liebman** [comment]
If you removed the 10 second interval then you will need to re-tune the PID constants, they are set for samples every 10 seconds. sampling faster that they will make it go crazy.

**Comment by liebman** [comment]
`time_t PPS::getTime(struct timeval* tv)` is just returning a consistent set of seconds and microseconds.

> I understand that the _data->pps_time can be changed after tv->tv_sec = _data->pps_time but if we allow tv->tv_usec = 999999 (only 1 us is left) then on the return point the _data->pps_time could be incremented.

It's ok that `_data->pps_time` was incremented as long as the value we fetched from the timer (microseconds) happened in the same second as the value we copied from `_data->pps_time`.  If teh second rolled over BEFORE we grabbed the microseconds then we would return a value almost one second off (second value from the previous second and the low microsecond value from the current second).

**Comment by dizcza** [comment]
> If you removed the 10 second interval then you will need to re-tune the PID constants, they are set for samples every 10 seconds. sampling faster that they will make it go crazy.

In your implementation, `manageDrift()` is executed on each call of the `SyncManager.process()` and only once in a while (after 10 seconds and magic conditions with microseconds) it's skipped

https://github.com/liebman/esp32-gps-ntp/blob/29216337f7670a6b62a12c4533979c85efc3f772/main/SyncManager.cpp#L342-L372

**Comment by liebman** [comment]
> > If you removed the 10 second interval then you will need to re-tune the PID constants, they are set for samples every 10 seconds. sampling faster that they will make it go crazy.
> 
> In your implementation, `manageDrift()` is executed on each call of the `SyncManager.process()` and only once in a while (after 10 seconds and magic conditions with microseconds) it's skipped
> 
You are indeed correct. PID interval is handled in manageDrift()

**Comment by liebman** [comment]
I remember what these values are for `gps_tv.tv_usec > 800000
        && gps_tv.tv_usec < 900000`.  This is to insure that it is AFTER the GPS serial messages with the timestamp for the current second have been processed, and not too close to the end of the second so we don't get into a race condition.

**Comment by dizcza** [comment]
So I
1. Moved PPS interrupts from two devices to different GPIO groups.
2. Added back the interval of `>10` seconds in the `SyncManager.process()` function.
3. Added the change you made https://github.com/liebman/esp32-gps-ntp/blob/29216337f7670a6b62a12c4533979c85efc3f772/main/SyncManager.cpp#L346-L357

and the issue with frequent `setTime()` disappeared (the app has been running for 10 hours). I don't know which step has fixed this, my guess would be the latter.

----

> You are indeed correct. PID interval is handled in manageDrift()

So they are sampled every second, not every 10 seconds. Anyway, this is a minor concern.

----

> I remember what these values are for gps_tv.tv_usec > 800000 && gps_tv.tv_usec < 900000. This is to insure that it is AFTER the GPS serial messages with the timestamp for the current second have been processed, and not too close to the end of the second so we don't get into a race condition.

So this is a validity check for GPS parsed seconds. Don't know what a race condition could be though - between RTC and GPS? Either way, wouldn't it make sense then to await for GPS_PARSED events to come in a loop? Rather than relying on hardcoded time constants. GPS thread can enqueue messages to SyncManager or signal to it with direct thread-to-thread communication. SyncManager awaits these GPS_PARSED events.

----

You've missed several debug `if`s in the latest refactoring:

```
$ grep -RnP -A5 "#if +[10]" .

./main/highint5.S:143:#if 1
./main/highint5.S-144-    /* use if double interrupts? */
./main/highint5.S-145-    memw
./main/highint5.S-146-    l32i    a4, a5, STATUS_OFFSET
./main/highint5.S-147-#endif
./main/highint5.S-148-
--
./main/DS3231.cpp:71:#if 0
./main/DS3231.cpp-72-    //
./main/DS3231.cpp-73-    // if the age offset is outside a normal range then zero it!
./main/DS3231.cpp-74-    //  (30 is > 2ppm)
./main/DS3231.cpp-75-    if (abs(_age_offset) >= 30)
./main/DS3231.cpp-76-    {
--
./main/DS3231.cpp:85:#if 0
./main/DS3231.cpp-86-    writeReg(AGEOFFSET, 0);
./main/DS3231.cpp-87-    updateReg(CONTROL, CONV, CONV);
./main/DS3231.cpp-88-#endif
./main/DS3231.cpp-89-
./main/DS3231.cpp-90-    return true;
```

BTW, I've tried removing these lines

```
./main/highint5.S:143:#if 1
./main/highint5.S-144-    /* use if double interrupts? */
./main/highint5.S-145-    memw
./main/highint5.S-146-    l32i    a4, a5, STATUS_OFFSET
./main/highint5.S-147-#endif
```

I didn't get any difference.

**Comment by dizcza** [comment]
Also, I find it strange for the PID algorithm to converge to different best aging offsets for the same temperature. I'm counting how many times (seconds) in 20 minutes the RTC is running with a particular aging offset while the PID alg is running. This determines the "bestness" of the aging offset. Under this measure, I get `-17 ... -19` values for the aging offset at `T=21.75 C`. The deviation seems nonnegligible. I'm thinking to substitute PID by a simpler algorithm, sort of moving average, that keeps track of the `offset` and tunes the aging register if the `offset` is above or below zero microseconds (or in a tolerable range `[-10, 10] us`).

Talking about temperature, the *change* in temperature influences the DS3231 clock. The datasheet tells us that the temperature calibration is issued every 90 seconds. So if I put the RTC outside the window, the temperature drops quickly and before the RTC reacts to a change in temperature, the clock will be offset by ~50...100 us. Doing GPS calibration constantly compensates for this and reacts faster. This is just a remark. I'm wondering if it makes sense to have a table of (`age_offset, temperature)` as many arduinists suggest. Once the temperature settles, I don't find a big difference in the best aging offset given its drift when the temperature is not changing.

**Comment by dizcza** [comment]
I must say that I do see `setTime` time corrections once I fix the aging offset to the best value and turn off the PID alg.
```
^[[0;33mW (22:43:17.040) SyncManager: ::recordOffset: RTC interval out of range: 500004^[[0m
^[[0;32mI (22:43:18.357) SyncManager: T 21.75, AGEOFFSET -19 (fixed), PPM 0.0141 (-16.0 us / 1133 s)^[[0m
^[[0;32mI (22:43:21.035) SyncManager: setTime succeeded; GPS microseconds=999800, loops=419990^[[0m
^[[0;33mW (22:43:21.057) SyncManager: time correction happened!  PPS offset=-16.000 us gps_time=1644101000 rtc_time=1644101001^[[0m
...
^[[0;32mI (03:45:50.046) SyncManager: GPS Interval: 1000009^[[0m
^[[0;32mI (03:45:50.054) SyncManager: GPS Min/Max: 1000008 / 1000010^[[0m
^[[0;32mI (03:45:50.061) SyncManager: GPS Short/Long: 0 / 0^[[0m
^[[0;32mI (03:45:50.073) SyncManager: RTC Interval: 1000009^[[0m
^[[0;32mI (03:45:50.080) SyncManager: RTC Min/Max: 1000009 / 1000017^[[0m
^[[0;32mI (03:45:50.088) SyncManager: RTC Short/Long: 6 / 2^[[0m
```

This happened each time I got `::recordOffset: RTC interval out of range`. Three times in 10 hours.

So in half an hour after the aging offset has been fixed the RTC time was off by one second. I'd tolerate this change but the PPS offset is only `-16 us` - that's what bothers me.

**Comment by dizcza** [comment]
Apologies for the overwhelming comments.

Another fix I found when I was browsing how to port outdated `timer.h` to new `gptimer.h` lib. The direct access to timer count you're using https://github.com/liebman/esp32-gps-ntp/blob/29216337f7670a6b62a12c4533979c85efc3f772/main/MicroSecondTimer.h#L52-L56

misses an important update that was introduced in https://github.com/espressif/esp-idf/commit/deea402cf487f70e9ce7f1b279a8f6fafa190b6c shortly before you created the `MicroSecondTimer.h` file. So it should be like this:

```c
    uint32_t inline IRAM_ATTR getValue()
    {
        TIMERG0.hw_timer[TIMER_0].update = 1;
        // Timer register is in a different clock domain from Timer hardware logic
        // We need to wait for the update to take effect before fetching the count value
        while (TIMERG0.hw_timer[TIMER_0].update) {}
        return TIMERG0.hw_timer[TIMER_0].cnt_low;
    }
```

**Comment by liebman** [comment]
Nice catch on the timer! 

Hmmm `SyncManager: ::recordOffset: RTC interval out of range: 500004` is interesting in that it looks like an interrupt occurred on or very near the positive edge of the RTC SQW signal. And was this with or without `/* use if double interrupts? */` (I don't see this on my hardware)

**Comment by dizcza** [comment]
> Hmmm SyncManager: ::recordOffset: RTC interval out of range: 500004 is interesting in that it looks like an interrupt occurred on or very near the positive edge of the RTC SQW signal. And was this with or without /* use if double interrupts? */ (I don't see this on my hardware)

This was with ` /* use if double interrupts? */`. I'm using `highint5.S` with no changes.

Yes, this seems suspicious.

```
$ grep "RTC interval out of" ignored/22-02-05.TXT 
W (22:43:17.040) SyncManager: ::recordOffset: RTC interval out of range: 500004
W (22:43:21.057) SyncManager: time correction happened!  PPS offset=-16.000 us gps_time=1644101000 rtc_time=1644101001
W (22:43:22.871) SyncManager: ::recordOffset: RTC interval out of range: 2000019
W (00:46:04.935) SyncManager: ::recordOffset: RTC interval out of range: 500004
W (00:46:09.941) SyncManager: time correction happened!  PPS offset=-81.625 us gps_time=1644108368 rtc_time=1644108369
W (00:46:10.941) SyncManager: ::recordOffset: RTC interval out of range: 2000019
W (03:45:43.035) SyncManager: ::recordOffset: RTC interval out of range: 500004
W (03:45:50.037) SyncManager: time correction happened!  PPS offset=-97.000 us gps_time=1644119148 rtc_time=1644119149
W (03:45:50.941) SyncManager: ::recordOffset: RTC interval out of range: 2000019
```

**Comment by liebman** [comment]
What pull-up do you have on the RTC SQW signal? And what pin is it on?

**Comment by dizcza** [comment]
No pull-up. As you do.

```
#define GPS_RX_PIN (GPIO_NUM_23)
#define GPS_TX_PIN (GPIO_NUM_19)
#define GPS_PPS_PIN ((gpio_num_t)GPIO_NUM_18)
#define RTC_PPS_PIN ((gpio_num_t)GPIO_NUM_33)
#define SDA_PIN (GPIO_NUM_4)
#define SCL_PIN (GPIO_NUM_22)

...

    // initialize I2C_NUM_0
    err = i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
    if (err != ESP_OK)
    {
        ESP_LOGE(TAG, "i2c_driver_install: I2C_NUM_%d %d (%s)", I2C_NUM_0, err, esp_err_to_name(err));
    }
    i2c_config_t conf;
    conf.mode = I2C_MODE_MASTER;
    conf.sda_io_num = SDA_PIN;
    conf.scl_io_num = SCL_PIN;
    conf.sda_pullup_en = GPIO_PULLUP_DISABLE;
    conf.scl_pullup_en = GPIO_PULLUP_DISABLE;
    conf.master.clk_speed = 400000;
    err = i2c_param_config(I2C_NUM_0, &conf);
```

**Comment by liebman** [comment]
It needs a pullup.  I have an external 10k on that signal.

**Comment by dizcza** [comment]
Ah, I see. True, didn't think about that. All right, I'll add one and let you know.

**Comment by liebman** [comment]
You should be able to use the internal pullup.

**Comment by dizcza** [comment]
> You should be able to use the internal pullup.

yes, that's why I'll try first. Add internal pull-up for both SDA and SCL.

If not succeeded, I'll add an external one.

**Comment by liebman** [comment]
I pushed the  timer updates, also added the same logic in `highint5.S`.  I did some tests adding to a counter in the wait loop.  I never saw it count so it must be a very rare occurrence.

**Comment by dizcza** [comment]
Neither internal nor external (with internal turned off) pull-up resistors attached to RTC sda and scl pins helped.

I'm looking at the `PPS.begin()` function. Have you attached external pull-up/pull-down resistors here? I typically use an internal pull-up or pull-down resistor with GPIO interrupts. Found none in your code.

**Comment by liebman** [comment]
External 10k (its in the schematic R4 [here](https://github.com/liebman/esp32-gps-ntp/blob/master/images/esp-gps-ntp.jpg))

**Comment by dizcza** [comment]
So I added an external 10k pull-up resistor for RTC SQW and a 10k pull-down resistor for GPS PPS (I think it's also needed though I didn't find one in your schematic), kept 10k external pull-ups for I2C and this didn't solve the issue. I got one such event in a night after I fixed the aging offset to the best value:

```
^[[0;33mW (01:26:14.120) SyncManager: ::recordOffset: RTC interval out of range: 500004^[[0m
^[[0;32mI (01:26:15.468) SyncManager: T 21.75, AGEOFFSET -17 (fixed), PPM 0.0010 (-10.1 us / 10294 s)^[[0m
^[[0;32mI (01:26:20.115) SyncManager: setTime succeeded; GPS microseconds=999800, loops=336818^[[0m
^[[0;33mW (01:26:20.126) SyncManager: time correction happened!  PPS offset=-10.000 us gps_time=1644283579 rtc_time=1644283580^[[0m
^[[0;32mI (01:26:20.134) SyncManager: GPS Interval: 1000009^[[0m
^[[0;32mI (01:26:20.142) SyncManager: GPS Min/Max: 1000008 / 1000010^[[0m
^[[0;32mI (01:26:20.150) SyncManager: GPS Short/Long: 0 / 2^[[0m
^[[0;32mI (01:26:20.158) SyncManager: RTC Interval: 1000009^[[0m
^[[0;32mI (01:26:20.165) SyncManager: RTC Min/Max: 1000009 / 1000014^[[0m
^[[0;32mI (01:26:20.173) SyncManager: RTC Short/Long: 2 / 2^[[0m
^[[0;33mW (01:26:21.931) SyncManager: ::recordOffset: RTC interval out of range: 2000019^[[0m
```

I'll try running the app without fixing the aging offset but I don't think it'll help. Even if it helps, the problem won't be solved.

I need to perform more long-running tests without resetting the clocks on these events and see what offsets in both seconds and microseconds I get.

-----

P.S. I added the change you made in https://github.com/liebman/esp32-gps-ntp/commit/42643aa624090f5227f2559f8a956769cfdf1a2e. I've also tried removing
```c
#if 1
    /* use if double interrupts? */
    memw
    l32i    a4, a5, STATUS_OFFSET
#endif
```
and the problem occurred with and without this statement.

**Comment by liebman** [comment]
Just a note on a "fixed" aging offset.  I've had this one running for 2 years,  At the time I found that it generally was 3 or 4.  Now it's generally 10 or 11.  (I did not track the values over all this time so its just 2 samples about 24 months apart)

**Comment by liebman** [comment]
Not sure how you have this constructed but I had issues with a lot of short/long RTC PPS values when I had this on a solderless breadboard, for some reason it was very noisy in my "lab".  Running on a manufactured PC board it's been much much better..

**Comment by dizcza** [comment]
I added a line to extract RTC I2C time and compare it with the RTC PPS time in seconds every time I see RTC-PPS and GPS-PPS mismatch.

```c
            struct tm tm;
            _rtc->getTime(&tm);
            time_t t_rtc_sec = mktime(&tm);
            ESP_LOGW(TAG, "PPS offset=%0.3f us gps_time=%ld rtc_time=%ld, RTC i2c time %ld",
                        offset, gps_tv.tv_sec, rtc_tv.tv_sec, t_rtc_sec);
```
This showed me the logs where RTC-PPS was off by 1 second though RTC I2C time was correct.
```
^[[0;33mW (04:20:03.928) SyncManager: PPS offset=-98.125 us gps_time=1644466802 rtc_time=1644466803, RTC i2c time 1644466802^[[0m

three hours later

^[[0;33mW (07:40:16.044) SyncManager: PPS offset=-243.000 us gps_time=1644478814 rtc_time=1644478815, RTC i2c time 1644478814^[[0m
^[[0;32mI (07:40:16.053) SyncManager: GPS Interval: 1000009^[[0m
^[[0;32mI (07:40:16.060) SyncManager: GPS Min/Max: 1000008 / 1000010^[[0m
^[[0;32mI (07:40:16.068) SyncManager: GPS Short/Long: 0 / 0^[[0m
^[[0;32mI (07:40:16.076) SyncManager: RTC Interval: 1000009^[[0m
^[[0;32mI (07:40:16.083) SyncManager: RTC Min/Max: 1000008 / 1000010^[[0m
^[[0;32mI (07:40:16.095) SyncManager: RTC Short/Long: 2 / 2^[[0m
```
So some SQW signals from an RTC are either lost or spurious. Even with 10k external resistors attached to a dev board (I won't be soldering it at the moment; though with these resistors attached it's become more stable). I guess we can adjust them as you do with GPS (if GPS parsed seconds differ, change GPS-PPS seconds accordingly): if RTC-PPS seconds differ from RTC I2C seconds, change the former to the latter.

What is strange is that I see

```
W (22:18:42.738) SyncManager: updating GPS Time PPS 1644445121 -> 1644445118 (-3 seconds)
I (22:18:42.930) SyncManager: setTime succeeded; GPS microseconds=999800, loops=310317
W (22:18:42.938) SyncManager: time correction happened! PPS offset=1.125 us gps_time=1644445118 rtc_time=1644445121, RTC i2c time 1644445121
```
and this happened in ~10 minutes the GPS was running after a GPS fix. I'm using cheap UBLOX Neo6M devices. But 3 seconds! Intolerable.

----

> Just a note on a "fixed" aging offset. I've had this one running for 2 years, At the time I found that it generally was 3 or 4. Now it's generally 10 or 11. (I did not track the values over all this time so its just 2 samples about 24 months apart)

That's interesting. Were the samples measured at different seasons? The diff in temperature could explain that. Otherwise, what have you done to the device that such a change occurred in two years? Different humidity? It was laying horizontally and then you put it vertically?
It'd be nice if you could add a new page in your device to keep track of the aging offset every week or so. I'm interested in how this progresses over time. My setup with PPS jitters is not that ideal for a lab.

**Comment by liebman** [comment]
> W (22:18:42.738) SyncManager: updating GPS Time PPS 1644445121 -> 1644445118 (-3 seconds)

Yea - I delay GPS valid because of this (20 minutes).  I believe it's due to these being "positioning" modules and not "timing" modules (harder to find and generally slightly more expensive).

**Comment by dizcza** [comment]
I'm sorry for keeping the issue stalled for months, I should have already closed it.

To give you some updates I've had over the past months (and give myself credit for keeping the discussion open), I've taken your idea but implemented the synchronization routine using MCPWM hardware (in the capture mode) available on ESP-32 boards. This hardware module allows one to precisely tick the duration of a pulse (with nanosecond precision). I ain't into assembly code, although lately, I've been doing some assembly fiddling with ULP, which actually reminded me of the time I was having a look at your assembly instructions and feeling dizzy.

Long story short, the solution I came up with is greatly influenced by your SyncManager. I even kept the PID constants (I was trying to change them with no luck). One remark though is that your simple PID algorithm is not stable once it converges. In other words, the age keeps jumping from 5 to 6 and back every 10 seconds or so. I ported some software filtering code from Wikipedia but it didn't help.

And yes, the "best" age value (which keeps the offset zero) changes gradually over time with the same env conditions.

So thank you for having cozy chatting back then. I'm closing the issue but I'll be keeping an eye on your repo to see if you actually get around the instability issue or just have fun with your assembly.

**Comment by liebman** [comment]
A note on the age offset - given that its an integer value the - 5 will be too low but 6 will be too high so it bounces back and forth because its using this to speed up and slow down the clock to keep the time correct.

**Comment by dizcza** [comment]
> A note on the age offset - given that its an integer value the - 5 will be too low but 6 will be too high so it bounces back and forth because its using this to speed up and slow down the clock to keep the time correct.

Yes, I understand. Sometimes it doesn't make sense to have precisely zero offset and force the AGE to bounce between 5 and 6, clogging my logs. What I was looking for is to add a kind of low pass filter to switch between 5 and 6 when the offset really accumulates (depends on the filter constants).
